// Completion Provider
// extensions/titan-core/src/providers/completion-provider.ts

import * as vscode from 'vscode';
import { AIService } from '../services/ai-service';

export class CompletionProvider implements vscode.CompletionItemProvider {
  private aiService: AIService;
  private lastCompletionTime: number = 0;
  private minDelay: number;

  constructor(aiService: AIService) {
    this.aiService = aiService;
    const config = vscode.workspace.getConfiguration('titan');
    this.minDelay = config.get('suggestions.delay') || 300;
  }

  async provideCompletionItems(
    document: vscode.TextDocument,
    position: vscode.Position,
    token: vscode.CancellationToken,
    context: vscode.CompletionContext
  ): Promise<vscode.CompletionItem[] | undefined> {
    // Check if suggestions are enabled
    const config = vscode.workspace.getConfiguration('titan');
    if (!config.get('suggestions.enabled')) {
      return undefined;
    }

    // Debounce completions
    const now = Date.now();
    if (now - this.lastCompletionTime < this.minDelay) {
      return undefined;
    }
    this.lastCompletionTime = now;

    // Get context
    const prefix = document.getText(
      new vscode.Range(new vscode.Position(Math.max(0, position.line - 10), 0), position)
    );
    
    const suffix = document.getText(
      new vscode.Range(position, new vscode.Position(Math.min(document.lineCount, position.line + 5), 0))
    );

    if (token.isCancellationRequested) return undefined;

    try {
      const completion = await this.aiService.complete(prefix, suffix, document.languageId);

      if (token.isCancellationRequested || !completion) return undefined;

      const item = new vscode.CompletionItem('Titan AI Suggestion', vscode.CompletionItemKind.Snippet);
      item.insertText = new vscode.SnippetString(completion);
      item.detail = 'AI-powered completion';
      item.documentation = new vscode.MarkdownString(`Generated by Titan AI\n\n\`\`\`${document.languageId}\n${completion}\n\`\`\``);
      item.preselect = true;
      item.sortText = '0'; // Ensure it appears first

      return [item];
    } catch {
      return undefined;
    }
  }
}
